# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "@elm-land/cli"

on:
  push:
    branches: [ main ]
    paths:
      - 'projects/cli/**'
  pull_request:
    paths:
      - 'projects/cli/**'

jobs:
  build:
    defaults:
      run:
        working-directory: projects/cli

    name: "Tests"
    runs-on: macos-12

    strategy:
      matrix:
        node-version: [16,18]

    steps:
      - name: "Checkout latest code"
        uses: actions/checkout@v3
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install NPM dependencies"
        run: npm ci
      - name: "Build Elm code generator"
        run: npm run setup
      - name: "Make elm-land available in terminal"
        run: npm link
      - name: "Run test suite"
        run: npm test
